#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""
File: colors.py
Description: Configuration file for Qtile window manager.
Author: Your Name
Date: YYYY-MM-DD
"""

# creemos una estructura de colores para nuestro tema
# en este caso, usaremos los colores de la paleta de colores de Dracula
# los datos estaran definidos asi: 
# color = {
#     "$scheme": {
#         "background": "color",
#     }
# }


colors   = {
   'gruvbox': {
         "background": "#282828",
         "foreground": "#ebdbb2",
         "comment": "#928374",
         "cyan": "#83a598",
         "green": "#b8bb26",
         "orange": "#fe8019",
         "pink": "#d3869b",
         "purple": "#d3869b",
         "red": "#fb4934",
         "yellow": "#fabd2f",
         "bright_blue": "#83a598",
         "bright_cyan": "#8ec07c",
         "bright_green": "#b8bb26",
         "bright_orange": "#fe8019",
         "bright_pink": "#d3869b",
         "bright_purple": "#d3869b",
         "bright_red": "#fb4934",
         "bright_yellow": "#fabd2f",
   },

   'dracula': {
        "background": "#282a36",
        "foreground": "#f8f8f2",
        "comment": "#6272a4",
        "cyan": "#8be9fd",
        "green": "#50fa7b",
        "orange": "#ffb86c",
        "pink": "#ff79c6",
        "purple": "#bd93f9",
        "red": "#ff5555",
        "yellow": "#f1fa8c",
        "bright_blue": "#8be9fd",
        "bright_cyan": "#8be9fd",
        "bright_green": "#50fa7b",
        "bright_orange": "#ffb86c",
        "bright_pink": "#ff79c6",
        "bright_purple": "#bd93f9",
        "bright_red": "#ff5555",
        "bright_yellow": "#f1fa8c",
    },

    'nord': {
        "background": "#2e3440",
        "foreground": "#d8dee9",
        "comment": "#4c566a",
        "cyan": "#88c0d0",
        "green": "#a3be8c",
        "orange": "#d08770",
        "pink": "#b48ead",
        "purple": "#b48ead",
        "red": "#bf616a",
        "yellow": "#ebcb8b",
        "bright_blue": "#81a1c1",
        "bright_cyan": "#8fbcbb",
        "bright_green": "#a3be8c",
        "bright_orange": "#d08770",
        "bright_pink": "#b48ead",
        "bright_purple": "#b48ead",
        "bright_red": "#bf616a",
        "bright_yellow": "#ebcb8b",
    },

    'solarized-dark': {
        "background": "#002b36",
        "foreground": "#839496",
        "comment": "#586e75",
        "cyan": "#2aa198",
        "green": "#859900",
        "orange": "#cb4b16",
        "pink": "#d33682",
        "purple": "#6c71c4",
        "red": "#dc322f",
        "yellow": "#b58900",
        "bright_blue": "#268bd2",
        "bright_cyan": "#2aa198",
        "bright_green": "#859900",
        "bright_orange": "#cb4b16",
        "bright_pink": "#d33682",
        "bright_purple": "#6c71c4",
        "bright_red": "#dc322f",
        "bright_yellow": "#b58900",
    },

    'one-dark': {
        "background": "#282c34",
        "foreground": "#abb2bf",
        "comment": "#5c6370",
        "cyan": "#56b6c2",
        "green": "#98c379",
        "orange": "#d19a66",
        "pink": "#e06c75",
        "purple": "#c678dd",
        "red": "#e06c75",
        "yellow": "#e5c07b",
        "bright_blue": "#61afef",
        "bright_cyan": "#56b6c2",
        "bright_green": "#98c379",
        "bright_orange": "#d19a66",
        "bright_pink": "#e06c75",
        "bright_purple": "#c678dd",
        "bright_red": "#e06c75",
        "bright_yellow": "#e5c07b",
    },
    'ayu-dark': {
        "background": "#0a0e14",
        "foreground": "#b3b3b3",
        "comment": "#445069",
        "cyan": "#5dd5d5",
        "green": "#91b362",
        "orange": "#f29668",
        "pink": "#ff8f40",
        "purple": "#f28779",
        "red": "#ea6c73",
        "yellow": "#e6b673",
        "bright_blue": "#5dd5d5",
        "bright_cyan": "#5dd5d5",
        "bright_green": "#91b362",
        "bright_orange": "#ff8f40",
        "bright_pink": "#ff8f40",
        "bright_purple": "#f28779",
        "bright_red": "#ea6c73",
        "bright_yellow": "#e6b673",
    },
    'catppuccin': {
        "background": "#1e1e2e",
        "foreground": "#cdd6f4",
        "comment": "#6c7086",
        "cyan": "#94e2d5",
        "green": "#a6e3a1",
        "orange": "#fab387",
        "pink": "#f5c2e7",
        "purple": "#cba6f7",
        "red": "#f38ba8",
        "yellow": "#f9e2af",
        "bright_blue": "#89b4fa",
        "bright_cyan": "#94e2d5",
        "bright_green": "#a6e3a1",
        "bright_orange": "#fab387",
        "bright_pink": "#f5c2e7",
        "bright_purple": "#cba6f7",
        "bright_red": "#f38ba8",
        "bright_yellow": "#f9e2af",
    },
    'tokyo-night': {
        "background": "#1a1b26",
        "foreground": "#a9b1d6",
        "comment": "#444b6a",
        "cyan": "#4fd6be",
        "green": "#9ece6a",
        "orange": "#ff9e64",
        "pink": "#ff7594",
        "purple": "#bb9af7",
        "red": "#f7768e",
        "yellow": "#e0af68",
        "bright_blue": "#2ac3de",
        "bright_cyan": "#4fd6be",
        "bright_green": "#9ece6a",
        "bright_orange": "#ff9e64",
        "bright_pink": "#ff7594",
        "bright_purple": "#bb9af7",
        "bright_red": "#f7768e",
        "bright_yellow": "#e0af68",
    }
}
